# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# clone directory
clone_folder: c:\projects\osre

# branches to build
branches:
  # whitelist
  only:
    - master

platform:
    - x86
    - x64

configuration:
  - 14 2015
  - 12 2013
  #- MinGW
  #- 10 2010 # only works for x86

init:
- if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )

install:
# Make compiler command line tools available
- call c:\projects\osre\scripts\appveyor\compiler_setup.bat

build_script:
- cd c:\projects\osre
- if "%platform%" equ "x64" (cmake CMakeLists.txt -G "Visual Studio %Configuration% Win64")
- if "%platform%" equ "x86" (cmake CMakeLists.txt -G "Visual Studio %Configuration%")
- if "%platform%" equ "x64" (msbuild /m /p:Configuration=Release /p:Platform="x64" osre.sln)
- if "%platform%" equ "x86" (msbuild /m /p:Configuration=Release /p:Platform="Win32" osre.sln)

after_build:
  - 7z a osre.7z c:\projects\osre\bin\release\* c:\projects\osre\lib\release\*

artifacts:
  - path: osre.7z
    name: osre_lib
